### PR TITLE
Have the driver version display as major.minor.revision.build

### PR DESCRIPTION
**Pull request by selvanair**
The driver version (taken from the INF) and the file version of
tap0901.sys file (from its resource) will now display like
9.22.1.601.

The driver details tab will continue to show the text form of
the version as "major.minor.revision major/minor".
Eg., "9.22.1 9/22"

Signed-off-by: Selva Nair <selva.nair@gmail.com>

---
Appears to work fine as in the image below, but I would like to do some tests with a properly signed version.
capture

### CODE REVIEW

**Comment by selvanair** [comment]
date change reverted

**Comment by selvanair** [comment]
@mattock : does this work as expected in your new test setup?

**Comment by mattock** [comment]
@selvanair I will test this once the test instances are up and accepting remote commands. I'm not quite there yet.

**Comment by cron2** [comment]
I have tested Samuli's latest signed win10 driver, and it seems to do the right thing.  Driver identifies in OpenVPN as 9.23, and in the "driver config" pane, it says "Treiberversion: 9.23.1.601".  File version of tap0901.sys is "9.23.1 9/23", whatever *that* signifies, but it sort of all has the same base info.  Better than before :-)

**Pull request merged**
