### PR TITLE
Add ARM64 files to installer

### PR DESCRIPTION
**Pull request by jkunkee**

### CODE REVIEW

**Comment by jkunkee** [comment]
This passes my smoke test on ARM64. No code has changed since the 6.30 bump, so this should be good for x64 and x86 as well.

**Comment by jkunkee** [comment]
rebase onto master

**Comment by cron2** [comment]
Hi,

On Tue, May 08, 2018 at 05:09:24PM -0700, Jon Kunkee wrote:
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OpenVPN/tap-windows6/pull/57

On a cursory glance, this looks all logical.  Of course the magic is
in wow.nsh, which I won't claim to understand at all...

So this is "testing" again :-)

Jon, is there a way to test on ARM64 without buying a Surface tablet?

(I do have an rPI 3, but I assume that this won't do...)

Anything virtual?

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by jkunkee** [comment]
Unfortunately we don't have anything virtual at the moment, no. I'm happy to test things, though :)

**Comment by cron2** [comment]
It passed the smoke tests, and has been left out in the open for way too long, so merging it now.

**Pull request merged**
