### PR TITLE
Use IF_TYPE_ETHERNET_CSMACD

### PR DESCRIPTION
**Pull request by lygstate**
I wanna use CI to create a driver and downlaod it to testing

### CODE REVIEW

**Comment by lygstate** [comment]
Indeed the CI are not working at all.

**Comment by lygstate** [comment]
it's a broken CI

**Review by selvanair — COMMENTED** [review]
This was changed to VIRTUAL for a reason (see PR #84 ) . Why would you want to revert it?

**Comment by schwabe** [comment]
I don't think this repo even has an automatic CI

**Pull request closed without merging**
