### PR TITLE
Added check to create dist folder if its does not exists already and Customising name of NSIS exe package

### PR DESCRIPTION
**Pull request by shkpk**
This PR is to fix issue #132

### CODE REVIEW

**Comment by mattock** [comment]
@shkpk afaics this look good. Did you test building an MSM with this?

**Comment by shkpk** [comment]
> @shkpk afaics this look good. Did you test building an MSM with this?

@mattock this change is specifically targeting NSIS build. There is no code change effecting MSM.

**Comment by shkpk** [comment]
> > @shkpk afaics this look good. Did you test building an MSM with this?
> 
> @mattock this change is specifically targeting NSIS build. There is no code change effecting MSM.

I updated msm packages to use `PRODUCT_PACKAGE_NAME` as NSIS installer for customized name of exe/msm

**Comment by lstipakov** [comment]
I compile-tested MSM part and it looks fine. Could you rebase your PR on top of master and squash to the reasonable amount of commits?

**Comment by shkpk** [comment]
> I compile-tested MSM part and it looks fine. Could you rebase your PR on top of master and squash to the reasonable amount of commits?

Done 👍

**Comment by mattock** [comment]
There are still several merge commits and two commits that unnecessary share the same commit message. I would just do

```
git reset --soft <last-upstream-commit-id>
```
Then add/commit the modified files from scratch.

**Comment by shkpk** [comment]
@mattock  Opened new PR https://github.com/OpenVPN/tap-windows6/pull/136

**Pull request closed without merging**
